spring:
  application:
    name: ai
  ai:
    ollama:
      base-url: http://${AI_DOCKER_HOST:localhost}:11434
      chat:
        options:
          model: qwen3:0.6b
      embedding:
        options:
          model: mxbai-embed-large
    vectorstore:
      pgvector:
        initialize-schema: true

  datasource:

    # This for Local Postgres store
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test
#    username:
#    password:

# This for PgVector
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB}
    username: ${POSTGRES_USER}    # Pass the user and pswrd to run the database
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true
      close-timeout: 60s
      operation-timeout: 60s

    consumer:
      group-id: log-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: all
#      retries: 3
#      properties:
#        enable.idempotence: true

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG